### ISSUE TITLE
Pattern title and classification missing

### ISSUE THREAD

**Issue by iluwatar** [iluwatar/java-design-patterns-vuepress-web#2]
- Run the website according to the instructions in [README.md](https://github.com/iluwatar/java-design-patterns-vuepress-web/blob/main/README.md)
- Open one of the patterns e.g. http://localhost:8080/patterns/abstract-document/ and compare to https://java-design-patterns.com/patterns/abstract-document/

The pattern's title and categories are missing from the page. The data is included in [the frontmatter](https://vuepress.vuejs.org/guide/markdown.html#frontmatter) of each page and we should find a way to get that data visible on the page.

**Comment by nicolasalarconrapela** [comment]
Can I take care of it?

**Comment by ohbus** [comment]
Go ahead @nicolasalarconrapela!

Please mention a timeline when can we expect a PR against this.

**Comment by iluwatar** [comment]
Excellent to have another contributor to the new website skeleton! You're warmly welcome @nicolasalarconrapela 👍🏻

**Comment by nicolasalarconrapela** [comment]
Hello Jedi's,

I have been researching the bug in the VuePress universe. I am sorry to inform you that I have not been able to find the evil that lurks in this bug. I suspect this is the Vuepress versions or something I have overlooked that causes FrontMatter to not compile.

However, I have found a VuePress theme ([theme-hope](https://github.com/vuepress-theme-hope/vuepress-theme-hope)) that shows the title of the document although for the category it would have to change categories by category in all README's

Below I attach an image of what it would look like:

![image](https://user-images.githubusercontent.com/23703592/116284341-ab400f80-a795-11eb-8ff1-b0680ef4c995.png)

Although in the image it is not appreciated correctly, `theme-hope` has interesting functionalities such as activating or deactivating dark mode or, for example, being able to copy a fragment of the code to the clipboard. Even so, when I implemented it for the first time on the web I realized that there were details such as the style, the letter, etc. that did not fit very well. I can't say if it's because you need a specific configuration or because there are plugins in `theme-hope` that the web doesn't support; But what I do know is that it would take time to investigate it further and give a definitive conclusion.

As mentioned above, the main problem with this implementation is that the [java-design-patterns](https://github.com/iluwatar/java-design-patterns) repository  would have to be modified to suit the `theme-hope`. A positive point is with this the refactoring could be automated and that it would serve for future massive refactorings and improvements in the project (_It is not necessary to say that the performance of this automation would be carried out by me_)

Hence I need the opinion of the '_Council_'.

Greetings.

**Comment by iluwatar** [comment]
Thanks @nicolasalarconrapela for looking into this. I briefly looked at theme-hope and understand it contains all the features of the default theme and a ton more, so in that sense it looks good to me. The theme also seems to be quite popular and actively maintained. My question at this point is what are the exact changes we would need to do in java-design-patterns repository? I'm asking because the current production website would need to be changed to support this as well.

**Comment by nicolasalarconrapela** [comment]
I have tried various combinations but the best option for the metadata is:

```diff
-- layout: pattern
title: Abstract Document
-- folder: abstract-document
-- permalink: /patterns/abstract-document/

-- categories: Structural
++ category: Structural

tags: 
- Cloud distributed
- Decoupling
- Microservices
```

I suppose that this will break the state of the other web page, therefore this change would be the last one and unify them at the last moment and when doing it eliminate the other web (_two webs under maintenance, I think, which is going to be much more expensive than one alone_)

**Comment by iluwatar** [comment]
Thanks @nicolasalarconrapela. I see that layout, folder and permalink would not be needed anymore and categories would change to category. I'm trying to understand what is happening in the tags section since the data has been removed in the diff. Can you elaborate on what's going on?

**Comment by nicolasalarconrapela** [comment]
> Thanks @nicolasalarconrapela. I see that layout, folder and permalink would not be needed anymore and categories would change to category. I'm trying to understand what is happening in the tags section since the data has been removed in the diff. Can you elaborate on what's going on?

 Forgiveness 😬!! This is just a visual error ... By not indenting it the diff has taken it as a deletion and it is not. I have already updated the comment and yes, the tags would remain unchanged. _I hope I didn't drive you crazy too much_.

**Comment by iluwatar** [comment]
No problem, now I think it looks much clearer 🙂 I also think that the proposed format is acceptable so we can go ahead with the current plan of using the theme-hope and doing the metadata format change at the end when we shut down the old web site and migrate to the new one.

**Comment by nicolasalarconrapela** [comment]
Well, nothing I get to work and I will inform ...

**Comment by iluwatar** [comment]
I ended up implementing this myself according to the discussion above. The application now uses https://github.com/vuepress-theme-hope/vuepress-theme-hope. [Java Design Patterns repository](https://github.com/iluwatar/java-design-patterns) has a special branch `vuepress` where the frontmatters have been updated to the [new format](https://github.com/iluwatar/java-design-patterns-vuepress-web/issues/2#issuecomment-833434632).

**Comment by iluwatar** [comment]
The issue has been resolved and the results can be checked on the live automatically deployed website. At the moment the patterns are accessible using direct URLs only, but here's one example: https://jdp-vue.netlify.app/patterns/adapter/
